backend:
    name: git-gateway
    branch: base
  
  media_folder: static/img
  public_folder: /img
  
  collections:
    - name: "adventure"
      label: "Adventure"
      folder: "content/adventure"
      create: true
      slug: "{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
        - {label: "Tags", name: "tags", widget: "list"}
